version: '3'
services:
  anhar-service:
    build: ./
    environment:
      OTEL_METRICS_EXPORTER: "logging"
      OTEL_LOGS_EXPORTER: "logging"
      OTEL_TRACES_EXPORTER: "jaeger"
      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14250"
    ports:
      - "8080:8080"
  jaeger-all-in-one:
      container_name: jaeger
      image: jaegertracing/all-in-one:latest
      environment:
        - COLLECTOR_OTLP_ENABLED=true
      restart: always
      ports:
        - "16686:16686"
        - "14250"
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: opentelemetry
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5433"