version: '3'
services:
#  anhar-service:
#    build: ./
#    environment:
#      OTEL_METRICS_EXPORTER: "prometheus"
#      OTEL_LOGS_EXPORTER: "logging"
#      OTEL_TRACES_EXPORTER: "jaeger,zipkin"
#      OTEL_EXPORTER_JAEGER_ENDPOINT: "http://jaeger:14250"
#      OTEL_EXPORTER_ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
#      OTEL_EXPORTER_PROMETHEUS_HOST: "0.0.0.0"
#      OTEL_EXPORTER_PROMETHEUS_PORT: "9464"
#      OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo:4317"
#      OTEL_EXPORTER_OTLP_INSECURE: true
#      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/opentelemetry"
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
  prometheus:
      container_name: prometheus
      image: prom/prometheus
      volumes:
        - ./docker/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml
      command:
        - --config.file=/etc/prometheus/prometheus.yml
      restart: always
      ports:
        - '9090:9090'
      extra_hosts:
        - "host.docker.internal:host-gateway"

  collector:
    image: otel/opentelemetry-collector-contrib:0.92.0
    volumes:
      - ./otel-config.yaml:/otel-config.yaml
    command: ["--config=/otel-config.yaml"]
    expose:
      - "4317"
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      - "4317:4317"   # otlp receiver
    depends_on:
      - tempo
  grafana:
      container_name: grafana
      image: grafana/grafana
#      volumes:
#        - ./docker/grafana/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      restart: always
      ports:
        - "3000:3000"
      depends_on:
        - prometheus
  loki:
    container_name: loki
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    ports:
      - "3100:3100"
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: opentelemetry
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yml
    ports:
      - "3200:3200"   # tempo
      - "4317"  # otlp grpc
  mysql:
      container_name: mysql
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      extra_hosts: ['host.docker.internal:host-gateway']
      environment:
        MYSQL_ROOT_PASSWORD: password
      ports:
        - 3307:3306
  zipkin-all-in-one:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"